### PR TITLE
add github CI

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
Alright this is ready. With this PR, there's working MSYS2 support.

**Comment by ZerBea** [comment]
Thanks. Merged.

But all in all, I'm not happy to support commercial operating systems  (neither Windows nor Apple).
PRs containing extra C functions designed for Windows or Apple will be rejected.

**Comment by ZerBea** [comment]
Starting with kernel 6.3 the kernel hackers decided to drop WIRELESS EXTENSIONS (WEXT) on new WiFi hardware.
https://github.com/aircrack-ng/aircrack-ng/discussions/2543
You may have noticed that, at the same time, starting with v 6.3.0, hcxdumptool is going back to the roots, because I learned that it was not a good idea to add all possible features and to support all operating systems.
A Jack of trades, packed with plenty of features and running on all operating systems, might be nice, but it is a toothless tiger that is hard to maintain.
I don't want to learn the same lesson on hcxtools.

**Comment by neheb** [comment]
to be fair, MSYS2 is not commercial. It has enough boilerplate to make it easy to build hcxtools, except for the ones that use pwd.h.

For MSVC, getopt needs a solution at a minimum. I have a commit locally that builds everything as C++ instead of C but I'm sure that will be rejected.

**Comment by neheb** [comment]
@ZerBea btw for this PR to work properly, Actions need to be enabled for this github repository.

**Comment by neheb** [comment]
C++ is as simple as https://github.com/neheb/hcxtools/commit/f1a029b21eab58be79dd60e4d0bb41455d1cef0f

I have it locally as static analyzers work better with C++. C++ is also needed to get rid of getopt and get hcxtools potentially building under MSVC. I probably won't be posting such a thing.

I should note most of the reason for this is to get it built on MSYS2 as OpenCL drivers for my hardware are only available on Windows.

**Comment by ZerBea** [comment]
BTW:
How can I disable -Wpedantic on git actions?

**Comment by neheb** [comment]
https://github.com/ZerBea/hcxtools/blob/master/.github/workflows/meson.yml#L52

set to 2 or 1 everywhere.

**Comment by ZerBea** [comment]
Thanks, I got it (after showing hidden directories).

**Comment by ZerBea** [comment]
Is there any good reason why you added Ubuntu-clang?

**Comment by ZerBea** [comment]
Regarding the requirements as mentioned in README.md, this simple workflow is more than enough:
https://github.com/ZerBea/hcxdumptool/blob/master/.github/workflows/cpush.yml
Runtime is ~18s (compared to your complex one ~ 6m 17s).
There are some dependencies to install (like libcurl4-gnutls-dev), but I don't think we and up > 6 minutes.

**Comment by neheb** [comment]
The CI file was taken and adapted from exiv2 where I try to have the widest compiler variation possible to make sure it builds everywhere. I don't see an issue with doing the same here. It allowed me to find missing headers and whatnot.

**Comment by ZerBea** [comment]
There is absolutely no issue.

After adding (fixing related warnings) the reduced workflow is more than enough for me.
If all compiles without errors and no warnings on Arch and Raspbian testing, it is fine. And if everything is working as expected it is ok. I don't want to make things more complicated than they really are.

BTW:
Using ubuntu is a philosophy. If you take a look at ubuntu package search result:
https://packages.ubuntu.com/search?keywords=hcxtools&searchon=names&suite=jammy&section=all
you'll notice that the actual, tested and recommended hcxtools version is 6.2.5:
`6.2.5-2: amd64 arm64 armhf ppc64el riscv64 s390x`

It is the decision of the user to stay on 22.04 so he have to live with hcxdumptool/hcxtools v6.2.5
For me there is no need to test latest git head on 22.04.

I don't claim that hcxdumptool and hcxtools are running on all systems compiled by all compilers. README.md is showing clear recommendations. Following this recommendations, a user get benefit of all tools.

**Comment by neheb** [comment]
Fair enough. It won't work if you try to compile under MSYS2, which is why I added the meson build.

**Comment by ZerBea** [comment]
I know and mentioned that in README.md:
"Unsupported: Windows OS, macOS, Android, emulators or wrappers!"

But it shouldn't be a problem for an experienced user to port it to his environment.
I'm running e.g. a headless version of hcxdumptool on the Raspberry which is different to the Desktop version.
There is no all-in-wonder version.

**Pull request merged**
