### PR TITLE
added feat: let user define ESSID of Beacon, useful for cloaked ESSID

### PR DESCRIPTION
**Pull request by gcarmix**
Added feature to let user indicate ESSID when missing from pcap file (cloaked ESSID).

When working with cloaked ESSID the Beacon packet does not contain the ESSID name necessary to generate the hash. With this new option it is now possible to manually add ESSID (taken from airodump, kismet...)

### CODE REVIEW

**Comment by ZerBea** [comment]
Not merged, because this commit will replace all(!) existing ESSIDs of a dump file with the user defined one which lead to invalid message pairs.
I recommend to use hcxlabtool/hcxdumptool to attack and capture, because (in contrast to airodump-ng and kismet), hcxdumptool/hcxlabtool does not depend on BEACON frames.

**Comment by gcarmix** [comment]
Obviously the option should be used only when you have a pcap file with a single ESSID, for example this is always the case of Kismet, in that case the problem that you mentioned does not occur, and the hcxpcapngtool, without this option can't be used

**Comment by ZerBea** [comment]
Exactly this is the problem of all "old school" dump tools.
But anyway, from my point of view, a dump file that doesn't contain all mandatory information to calculate a valid message pair is garbage.

**Comment by ZerBea** [comment]
The problem of a missing ESSID doesn't occur on hcxdumptool - hcxpcapngtool combination.
After a few seconds, hcxdumptool retrieved the HIDDEN ESSID:
```
$ sudo hcxdumptool -i wlp39s0f3u1u1u2 -c 13 --enable_status=15  -o test.pcapng
initialization of hcxdumptool 6.2.6-1-g7ad10d9 (depending on the capabilities of the device, this may take some time)...

start capturing (stop with ctrl+c)
NMEA 0183 SENTENCE........: N/A
PHYSICAL INTERFACE........: phy0
INTERFACE NAME............: wlp39s0f3u1u1u2
INTERFACE PROTOCOL........: IEEE 802.11
INTERFACE TX POWER........: 20 dBm (lowest value reported by the device)
INTERFACE HARDWARE MAC....: 00e0614861dd (not used for the attack)
INTERFACE VIRTUAL MAC.....: 00e0614861dd (not used for the attack)
DRIVER....................: mt7601u
DRIVER VERSION............: 5.17.4-arch1-1
DRIVER FIRMWARE VERSION...: N/A
openSSL version...........: 1.1
ERRORMAX..................: 100 errors
BPF code blocks...........: 0
FILTERLIST ACCESS POINT...: 0 entries
FILTERLIST CLIENT.........: 0 entries
FILTERMODE................: unused
WEAK CANDIDATE............: 12345678
ESSID list................: 0 entries
ACCESS POINT (ROGUE)......: 000d58c1ce00 (BROADCAST WILDCARD used for the attack)
ACCESS POINT (ROGUE)......: 000d58c1ce01 (BROADCAST OPEN used for the attack)
ACCESS POINT (ROGUE)......: 000d58c1ce02 (used for the attack and incremented on every new client)
CLIENT (ROGUE)............: c02250adb8f5
EAPOLTIMEOUT..............: 20000 usec
EAPOLEAPTIMEOUT...........: 2500000 usec
REPLAYCOUNT...............: 61716
ANONCE....................: 90fe8fc68c095d20c062252428a1654cef944a1a6de60667fde0cecad0f6fb2c
SNONCE....................: 601f7f1a918f639df71a84274c7f8f75ca00da57a24a8646c92305766c36c26b

TIME     FREQ/CH  MAC_DEST     MAC_SOURCE   ESSID [FRAME TYPE]
11:28:33 2472/13  ffffffffffff 0896d798e19e [WILDCARD BEACON]
11:28:34 2472/13  f6c56a62c874 0896d798e19e TEST-HIDDEN-ESSID [PROBERESPONSE]
11:28:39 2472/13  00e62d021987 0896d798e19e TEST-HIDDEN-ESSID [AUTHENTICATION]
11:28:39 2472/13  00e62d021987 0896d798e19e TEST-HIDDEN-ESSID [ASSOCIATION]
11:28:39 2472/13  00e62d021987 0896d798e19e TEST-HIDDEN-ESSID [EAPOL:M1M2ROGUE EAPOLTIME:2121 RC:61716 KDV:2 PSK:12345678]
11:28:40 2472/13  00e62d021987 0896d798e19e TEST-HIDDEN-ESSID [EAPOL:M2M3 EAPOLTIME:1950 RC:3 KDV:2]
11:28:40 2472/13  00e62d021987 0896d798e19e TEST-HIDDEN-ESSID [EAPOL:M3M4ZEROED EAPOLTIME:3329 RC:3 KDV:2]
```
Additional hcxdumptool got en entire 4way handshake and requested an additional EAPOL M2 from the client.

hcxpcapngtool convert it to a valid MESSAGE_PAIR:
```
$ hcxpcapngtool -o test.22000 test.pcapng
hcxpcapngtool 6.2.6-1-geb65226 reading from test.pcapng...

summary capture file
--------------------
file name................................: test.pcapng
version (pcapng).........................: 1.0
operating system.........................: Linux 5.17.4-arch1-1
application..............................: hcxdumptool 6.2.6-1-g7ad10d9
interface name...........................: wlp39s0f3u1u1u2
interface vendor.........................: 00e061
openSSL version..........................: 1.1
weak candidate...........................: 12345678
MAC ACCESS POINT.........................: 000da7e45010 (incremented on every new client)
MAC CLIENT...............................: d85dfbed3d72
REPLAYCOUNT..............................: 63710
ANONCE...................................: 97fea40e7b375d374ba3f6863eabd32f5c5f2cb0fe2932373767067a60dc1420
SNONCE...................................: 6d737e301102c9db56e82a4c7218ed6b2e01eca7e7db607ddb2e6dc4a5340c70
timestamp minimum (GMT)..................: 23.04.2022 11:33:16
timestamp maximum (GMT)..................: 23.04.2022 11:33:30
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11_RADIO (127)
endianess (capture system)...............: little endian
packets inside...........................: 147
packets received on 2.4 GHz..............: 136
ESSID (total unique).....................: 2
BEACON (total)...........................: 2
BEACON on 2.4 GHz channel (from IE_TAG)..: 13 
BEACON (SSID wildcard/unset).............: 1
PROBEREQUEST.............................: 1
PROBERESPONSE (total)....................: 2
AUTHENTICATION (total)...................: 3
AUTHENTICATION (OPEN SYSTEM).............: 3
ASSOCIATIONREQUEST (total)...............: 1
ASSOCIATIONREQUEST (PSK).................: 1
EAPOL messages (total)...................: 135
EAPOL RSN messages.......................: 135
EAPOLTIME gap (measured maximum usec)....: 21197
EAPOL ANONCE error corrections (NC)......: not detected
REPLAYCOUNT gap (measured maximum).......: 1
EAPOL M1 messages (total)................: 131
EAPOL M2 messages (total)................: 2
EAPOL M3 messages (total)................: 1
EAPOL M4 messages (total)................: 1
EAPOL pairs (total)......................: 13
EAPOL pairs (best).......................: 1
EAPOL ROGUE pairs........................: 1
EAPOL pairs written to 22000 hash file...: 1 (RC checked)
EAPOL M12E2 (challenge)..................: 1

frequency statistics from radiotap header (frequency: received packets)
-----------------------------------------------------------------------
 2412: 1	 2472: 135	


session summary
---------------
processed pcapng files................: 1
```

and hascat recovered the PSK from the converted MESSAGE_PAIR:
```
$ hashcat -m 22000 test.22000 cracked.txt.gz
hashcat (v6.2.5-396-g8ad2f176f) starting

CUDA API (CUDA 11.6)
====================
* Device #1: NVIDIA GeForce GTX 1080 Ti, 10607/11175 MB, 28MCU

OpenCL API (OpenCL 3.0 CUDA 11.6.127) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #2: NVIDIA GeForce GTX 1080 Ti, skipped

Minimum password length supported by kernel: 8
Maximum password length supported by kernel: 63

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Optimizers applied:
* Zero-Byte
* Single-Hash
* Single-Salt
* Slow-Hash-SIMD-LOOP

Watchdog: Temperature abort trigger set to 90c

Host memory required for this attack: 1475 MB

Dictionary cache built:
* Filename..: cracked.txt.gz
* Passwords.: 347295
* Bytes.....: 3766376
* Keyspace..: 347295
* Runtime...: 0 secs

ddfb0fa31cf0675b0ff88be532ad53b0:0896d798e19e:00e62d021987:TEST-HIDDEN-ESSID:12345678
                                                          
Session..........: hashcat
Status...........: Cracked
Hash.Mode........: 22000 (WPA-PBKDF2-PMKID+EAPOL)
Hash.Target......: test.22000
Time.Started.....: Sat Apr 23 11:36:55 2022 (0 secs)
Time.Estimated...: Sat Apr 23 11:36:55 2022 (0 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (cracked.txt.gz)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:   538.5 kH/s (5.39ms) @ Accel:4 Loops:256 Thr:512 Vec:1
Recovered.Total..: 1/1 (100.00%) Digests
Progress.........: 57344/347295 (16.51%)
Rejected.........: 0/57344 (0.00%)
Restore.Point....: 0/347295 (0.00%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:0-1
Candidate.Engine.: Device Generator
Candidates.#1....: 12345678 -> 05252000
Hardware.Mon.#1..: Temp: 55c Fan: 31% Util: 29% Core:1809MHz Mem:5005MHz Bus:16

Started: Sat Apr 23 11:36:53 2022
Stopped: Sat Apr 23 11:36:57 2022
```

That let me assume the missing ESSID is really a problem of kismet (and other tools that depend on a BEACON).

BTW:
The workflow mentioned above is much better than:
capturing by kismet, get the missing ESSID by airodump-ng and insert it by hand via hcxpacpngtool.

**Comment by gcarmix** [comment]
I understand your point, using the hcxtools toolsuite also for capturing the handshake removes the problem at all.

Anyway Kismet is very useful for other reasons, a webserver with a GUI, the integration with GPS  and maps. 
All these other features are often useful and not so fast to implement on your own.

Moreover with Kismet I don't need to use airodump-ng for capturing a cloaked ESSID, because Kismet adds in its DB records the ESSID name as soon as it collects it. 

Nevertheless I agree with you that the way Kismet captures the pcap introduces limitations. 

However, since I'm tied to Kismet for the other features, with few lines of code modified to your project I have been able to overcome this limitation and saved a lot of time.

**Comment by ZerBea** [comment]
I agree, kismet is a useful tool. But the developer should consider to store PROBERESPONSE, ASSOCIATION or REASSOCIATION frames instead of a BEACON. That would make live much easier.

**Comment by ZerBea** [comment]
s77rt added  it to multicapconverter and that should solve your problem:
https://github.com/s77rt/multicapconverter/

But you should consider to report an issue on kismet issue tracker:
https://github.com/kismetwireless/kismet/issues
kismet should store an ASSOCIATION/REASSOCIATION or PROBERESPONSE, especially if the SSID IE_TAG in the BEACON frame is unset or zeroed.

**Comment by gcarmix** [comment]
> s77rt added it to multicapconverter and that should solve your problem: https://github.com/s77rt/multicapconverter/

I know, it is my contribution ;)
Anyway yes, I should also open an issue on Kismet

**Comment by ZerBea** [comment]
multicapconverter is really a tool. I haven't noticed your PR on s77rt git.
 
There are a lot of problems, when trying to convert this pr-cleaned (ESSID +  handshake only) dump files:
If we have an ASSOCIATIONREQUEST/RESPONSE and a 4way handhshake or a PMKID:
we know that they came from the same authentication sequence. That prevent calculating invalid message pairs.
we know the cipher suite and the AK which is in use. That prevent calculating invalid message pairs. https://github.com/aircrack-ng/aircrack-ng/issues/2197

A SSID IE_TAG is always set (mandatory to calculate the PMK on pre-shared key authentications)  in ASSOCIATION and REASSOCIATION request frames:
https://mrncciew.com/2014/10/28/802-11-mgmt-association-reqresponse/
It is mandatory to calculate the PMK:
`PMK = PBKDF2_HMAC_SHA1(passphrase,essid,strlen(essid),4096,32)
`

**Comment by ZerBea** [comment]
great, thanks.

**Pull request closed without merging**
