### PR TITLE
Add optional userkey for wlancap2wpasec tool.

### PR DESCRIPTION
**Pull request by RealEnder**
This will associate submitted captures to user.

### CODE REVIEW

**Comment by ZerBea** [comment]
Great. Many users asked for this feature

**Comment by RealEnder** [comment]
Heh, didn't know that, just saw it now with the morning coffee :)

**Comment by strasharo** [comment]
Yay, that's so cool. I asked for it in the forums. :laughing:

**Comment by ZerBea** [comment]
done with latest commit.

**Comment by strasharo** [comment]
Awesome, thanks a lot.

**Pull request merged**
